version: 0.2

phases:
  build:
    commands:
      - echo "==== AWS CodeBuild 환경에서 테스트 시작 ===="
      - python test_code1.py
      - python test_code2.py
      - echo "==== 테스트 완료 ===="
artifacts:
  files:
    - '**/*' # 실행이 끝난 모든 파일을 S3로 보내라!